book/urls.py
from django.urls import path

from .views import (
    BookConfirmImportView,
    BookImportView,
    BookListView,
)

urlpatterns = [
    path('', BookListView.as_view(), name='list'),
    path('confirm/', BookConfirmImportView.as_view(), name='import_confirm'),
    path('import/', BookImportView.as_view(), name='import'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
]

book/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=30, blank=True)
    publication_date = models.DateField(null=True)
    pages = models.IntegerField(blank=True, null=True)
    price = models.DecimalField(max_digits=255, decimal_places=2)

    def __str__(self):
        return self.title

book/views.py
from custom_import_export.views import ImportView, ConfirmImportView

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .models import Book
from .resources import BookResource

# Create your views here.


class BookListView(generic.ListView):
    model = Book
    template_name = 'book/list.html'

class BookImportView(ImportView):
    """
    ImportView specific for model Book and resource BookResource
    """
    import_template_name = 'book/import.html'
    #: resource class
    resource_class = BookResource
    #: model to be imported
    model = Book


class BookConfirmImportView(ConfirmImportView):
    """
    ConfirmImportView specific for model Period and resource PeriodResource
    """
    import_template_name = 'book/import.html'
    #: resource class
    resource_class = BookResource
    #: model to be imported
    model = Book
    success_url = reverse_lazy('list')
    

book/templates/book/snippets/table.html
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Author</th>
              <th scope="col">Publication Date</th>
              <th scope="col">Pages</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
            
            {% for book in book_list %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ book.title }}</td>
              <td>{{ book.author }}</td>
              <td>{{ book.publication_date }}</td>
              <td>{{ book.pages }}</td>
              <td>{{ book.price }}</td>
            </tr>
            {% endfor %}
                
          </tbody>
    </table>
  </div>